### PR TITLE
Fix detection logic to determin Pull Requests from forked repo

### LINKED ISSUE #603: PullRequests *to* forked repo from the forked repo branch should be treated as normal PullRequest
Filed from https://github.com/reviewdog/action-shellcheck/issues/9

[isPRFromForkedRepo](https://github.com/reviewdog/reviewdog/blob/bfb8cbbf718172a6045f358bf81ac19542661524/cmd/reviewdog/doghouse.go#L253:6) should return false.

### PR DESCRIPTION
**Pull request by haya14busa**
- [x] Updated Unreleased section in [CHANGELOG](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md) or it's not notable changes.

Head and base repos can be the same *forked* repo, so refering to head
repo's "fork" field was not enough.

Fix #603

### CODE REVIEW

File: cienv/github_actions.go [hunk 1]
```diff
@@ -24,15 +24,22 @@ type GitHubEvent struct {
 	} `json:"head_commit"`
 }
 
+type GitHubRepo struct {
```
Comment (review-dog) [inline cienv/github_actions.go:27]: **[golint-circleci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
exported type GitHubRepo should have comment or be unexported

**Comment by haya14busa** [comment]
tested: https://github.com/review-dog/watchdogs/pull/2
