### PR TITLE
fix: SARIF parser: parse with no region result. fix originalOutput field

### LINKED ISSUE #1608: [BUG] Sarif format not working
```yml

vulnerability-scanning:
    runs-on: ubuntu-latest
    name: Vulnerability Scanning
    needs: [lint, test]
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: write
      actions: read
      issues: write
      pull-requests: write
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.14.0
        with:
          scan-type: 'config'
          scan-ref: ./
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-config-scan.sarif'

      - uses: actions/upload-artifact@v3
        with:
          name: trivy-config-scan.sarif
          path: trivy-config-scan.sarif

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.15.0

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo -n "$(cat trivy-config-scan.sarif)" | reviewdog -reporter=github-pr-review -f=sarif -level=info -diff="git diff FETCH_HEAD"
```

The command `echo -n "$(cat trivy-config-scan.sarif)" | reviewdog -reporter=github-pr-review -f=sarif -level=info -diff="git diff FETCH_HEAD"`

Doesn't produce anything, or even any log.

### PR DESCRIPTION
**Pull request by irgaly**
- [x] Updated Unreleased section in [CHANGELOG](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md) 

---

* [x] fix #1608
* [x] fix RDF originalOutput field

This PR supports SARIF file from Trivy.

Trivy SARIF sample
https://github.com/aquasecurity/trivy-sarif-demo/blob/d1968305c1133a0efd42bde85cd3bbefa68aa960/debug-trivy-results.sarif

SARIF v2.1.0 3.29.4 region property
https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541120

SARIF may not have a region property. This PR fixes reviewdog can parse SARIF with no region properties.

### CODE REVIEW

File: parser/sarif.go [hunk 1]
```diff
@@ -110,12 +109,9 @@ func (p *SarifParser) Parse(r io.Reader) ([]*rdf.Diagnostic, error) {
...
 					},
-					Code:        code,
-					Suggestions: suggestionsMap[path],
-					OriginalOutput: fmt.Sprintf(
-						"%v:%d:%d: %v: %v (%v)",
-						path, rng.Start.Line, getActualStartColumn(rng), level, message, ruleID,
-					),
+					Code:           code,
+					Suggestions:    suggestionsMap[path],
+					OriginalOutput: string(original),
```
Comment (irgaly) [inline parser/sarif.go:114]: OriginalOutput is SARIF JSON now.

**Review by shogo82148 — APPROVED** [review]
LGTM
