### PR TITLE
gitlab: fix base SHA

### LINKED ISSUE #249: Discussion in gitlab instance looks really strange.
image
Why I see this "download" buttons?

### PR DESCRIPTION
**Pull request by haya14busa**
Fix #249

### CODE REVIEW

File: service/gitlab/gitlab_mr_discussion.go [hunk 1]
```diff
@@ -15,6 +13,8 @@ import (
 	"github.com/reviewdog/reviewdog/service/serviceutil"
 )
 
+var X = "debug"
```
Comment (review-dog) [inline service/gitlab/gitlab_mr_discussion.go]: **[golint-circleci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
exported var X should have comment or be unexported

**Comment by haya14busa** [comment]
image
https://gitlab.com/reviewdog/reviewdog/merge_requests/295
